### ISSUE TITLE
NetBox 3.2 Support

### ISSUE THREAD

**Issue by ryanmerolle** [iDebugAll/phonebox_plugin#21]
[NetBox 3.2.0](https://github.com/netbox-community/netbox/releases/tag/v3.2.0) was just released and has a number of [extension improvements](https://github.com/netbox-community/netbox/issues/8333).

Furthermore, a [NetBox 3.2 plugin tutorial](https://github.com/netbox-community/netbox-plugin-tutorial) was released

**Comment by InsaneSplash** [comment]
`Traceback (most recent call last):
  File "netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/management/base.py", line 98, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/management/commands/migrate.py", line 91, in handle
    self.check(databases=[database])
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/urls/resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/urls.py", line 9, in <module>
    from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
  File "/opt/netbox/netbox/extras/plugins/urls.py", line 28, in <module>
    urlpatterns = import_object(f"{plugin_path}.urls.urlpatterns")
  File "/opt/netbox/netbox/extras/plugins/utils.py", line 31, in import_object
    spec.loader.exec_module(module)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/phonebox_plugin/urls.py", line 2, in <module>
    from . import views
  File "/opt/netbox/venv/lib64/python3.8/site-packages/phonebox_plugin/views.py", line 6, in <module>
    from . import forms
  File "/opt/netbox/venv/lib64/python3.8/site-packages/phonebox_plugin/forms.py", line 6, in <module>
    from extras.forms import AddRemoveTagsForm
ImportError: cannot import name 'AddRemoveTagsForm' from 'extras.forms' (/opt/netbox/netbox/extras/forms/__init__.py)`

**Comment by alexanderd24** [comment]
I'm getting the same error. Any thoughts?

**Comment by ryanmerolle** [comment]
> I'm getting the same error. Any thoughts?

If this is indeed a compatibility issue with NetBox 3.2, don't upgrade NetBox to 3.2 until this plugin adds support for 3.2 OR disable the plugin.

**Comment by Nino-Rey** [comment]
hopefully someone know how to fix the issue I'm getting the same error when upgrading to v3.2

**Comment by ryanmerolle** [comment]
> hopefully someone know how to fix the issue I'm getting the same error when upgrading to v3.2

Your only fix at this point is to disable the plugin.  You need to validate all the plugins you use work with major releases like 3.1 to 3.2 by checking with the plugin projects or by testing in your non-production netbox instance.

**Comment by InsaneSplash** [comment]
Such a pity

**Comment by iDebugAll** [comment]
Hi all. Thank you for your understanding and patience. 
I have just released a new plugin version `v0.0.4-beta.1` introducing a NetBox 3.2 compatibility.

**Comment by InsaneSplash** [comment]
I have installed it, no issues so far and I see we have Voice Circuits now :)

**Comment by alexanderd24** [comment]
I've tried to install, but got an error:
```
Running migrations:
  Applying phonebox_plugin.0001_initial...Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.DuplicateTable: relation "phonebox_plugin_number" already exists
```
How can I fix it?

**Comment by iDebugAll** [comment]
Latest PhoneBox plugin version 0.0.5-beta.1 is compatible with NetBox 3.2-3.4.
